### ISSUE TITLE
Resolver_Hints root None

### ISSUE THREAD

**Issue by bobo-le** [tfoxy/graphene-django-optimizer#19]
Hey, i am trying to retreive a list of categories and her translations with a custom filter.
I tried to use a resolver_hint from the examples:
![image](https://user-images.githubusercontent.com/15114434/56143667-3a0fd400-5fa1-11e9-9040-bc6d23be0237.png)

My models looks like that:
![image](https://user-images.githubusercontent.com/15114434/56143746-5a3f9300-5fa1-11e9-9154-81e50207ae30.png)

My Query is the following:
![image](https://user-images.githubusercontent.com/15114434/56143954-c91cec00-5fa1-11e9-813e-018484292763.png)

The response tells the following:
"NoneType' object has no attribute 'gql_language_code_de'"

As you see, the root variable is None:
![image](https://user-images.githubusercontent.com/15114434/56143941-c1f5de00-5fa1-11e9-9d77-acc1ef6192c8.png)

Can you tell me whats wrong with my code?

**Comment by tfoxy** [comment]
`root` is `None` at the root of a graph query. The `resolver_hints` would work if it was applied at the `translations` resolver. Is there a reason why `categoryList` receives `languageCode` instead of being `translations` the one with the argument?

**Comment by bobo-le** [comment]
So you mean like this?
![image](https://user-images.githubusercontent.com/15114434/56384981-1e653180-621e-11e9-8278-b5403c97f374.png)

I dont know how i can add the param to the translations field..

Thank you

**Comment by tfoxy** [comment]
Yes, like that!

In graphene, you can have the following schema:

```py
class CategoryType(DjangoObjectType):
    translations = graphene.List(
        CategoryTranslationType,
        language_code=graphene.String(),
    )

    class Meta:
        model = Category

    @gql_optimizer.resolver_hints(
        prefetch_related=lambda info, language_code: Prefetch(
            'translations',
            queryset=gql_optimizer.query(CategoryTranslation.objects.filter(language_code=language_code), info),
            to_attr='gql_translations_with_language_code_' + language_code,
        ),
    )
    def resolve_translations(root, info, language_code):
        return getattr(root, 'gql_translations_with_language_code_' + language_code)


class Query(object):
    category_list = graphene.List(CategoryType)

    def resolve_category_list(root, info):
        return gql_optimizer.query(Category.objects.all(), info)
```

**Comment by bobo-le** [comment]
Thank you very much!
