### ISSUE TITLE
Doesn't work with graphene 2.1.5?

### ISSUE THREAD

**Issue by cramshaw** [tfoxy/graphene-django-optimizer#25]
I just bumped my version of graphene to 2.1.5 from 2.1.3 and suddenly all the optimisation seems to have stopped. I have switched between 2.1.3 and 2.1.5 and it's definitely the cause. Most of 2.1.5 is doc updates - https://github.com/graphql-python/graphene/releases.

Django 2.2.2
Python 3.7

**Comment by bellini666** [comment]
Me too. I just started a project and am using the latest graphene available. I though this wasn't working actually =P

**Comment by cramshaw** [comment]
Glad it's not just me!
For anyone else, I have a PR seemingly fixing this - https://github.com/tfoxy/graphene-django-optimizer/pull/26

**Comment by bellini666** [comment]
> Glad it's not just me!
> For anyone else, I have a PR seemingly fixing this - #26

I commented in it, it indeed solves the problem.
