### ISSUE TITLE
Optimize pagination of relay connection fields

### ISSUE THREAD

**Issue by tfoxy** [tfoxy/graphene-django-optimizer#4]
Copied from https://github.com/tfoxy/graphene-django-optimizer/issues/1#issuecomment-419340157.

@tfoxy Do you use optimizers with any pagination? We're also using Apollo as the client and we want to provide cursor-based pagination. But we also have queries with nested connections e.g.:
```
{
  products(first: 10) {
    edges {
      node {
        name
        variants(first: 5) {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
```

Using just the ORM I'm able to fetch the data only with two DB queries:
```
Product.objects.prefetch_related('variants')
```

I'm trying to achieve the same in the API but unfortunately any pagination seems to break the prefetches as they do slicing on querysets internally which results in refetching objects that were already cached by `prefetch_related`.

**Comment by tfoxy** [comment]
Copied from https://github.com/tfoxy/graphene-django-optimizer/issues/1#issuecomment-419656992.

When there is pagination, the default implementation of prefetch_related doesn't work because it only prefetches the queryset.all() query. This library handles different kind of querysets for prefetch_related, so maybe it can optimize paginations. But right now it doesn't support it.

**Comment by tfoxy** [comment]
Copied from https://github.com/tfoxy/graphene-django-optimizer/issues/1#issuecomment-419677134.

@maarcingebala, are you sure `Product.objects.prefetch_related('variants')` works? Doesn't it fetch all the variants instead of just the first 5 from each product?

**Comment by maarcingebala** [comment]
@tfoxy Yes it does, but I still can benefit from prefetching data in one query instead of doing duplicated queries for each row of data.

Anyway, I managed to use prefetching by using optimization hints and the slightly modified version of `DjangoConnectionField`, as suggested [in this comment](https://github.com/graphql-python/graphene-django/issues/429#issuecomment-417634650). I'll keep experimenting with it. For now, I'd consider my question resolved, so you can close the issue.

**Comment by tfoxy** [comment]
I can understand the benefit of using `prefetch_related`. It's something that I also do sometimes even if I slice the collection later.
I think it's better to leave it as a manual optimization by using the optimization hints. Glad you managed to work it out.

**Comment by dani0805** [comment]
To my knowledge this is still an open issue. If you prefetch a query and then you go through a m2m or reverse FK resolve, the cache is ignored. The only solution I have solar is overriding ConnectionField like this:

```
class PrefetchingConnectionField(DjangoConnectionField):

    @classmethod
    def merge_querysets(cls, default_queryset, queryset):
        return queryset
```

I do not think this can be considered ok in the long run.

**Comment by maarcingebala** [comment]
@nwaxiomatic [Here is an example usage](https://github.com/mirumee/saleor/blob/master/saleor/graphql/product/types.py#L258) of optimization hints in my project. There is a `Product` model and each product can have multiple images (1-N relationship). From these images, we choose one as a product thumbnail to display in the UI.

Now, if we had a query that fetches first 5 products and a thumbnail for each of them:
```
{
  products(first: 5) {
    edges {
      node {
        name
        thumbnailUrl
      }
    }
  }
}
```

- Without optimization hints
For each product, Django would do a query to fetch all its images and return one as a thumbnail.

- With optimization hints
`@gql_optimizer.resolver_hints(prefetch_related='images')` tells Graphene to prefetch `images` relation when the `resolve_thumbnail_url` resolver is used. As a result, each time the thumbnail field is used, I'm able to take advantage of prefetched images and avoid duplicated database queries.

**Comment by nwaxiomatic** [comment]
@maarcingebala I see, so you aren't deconstructing this package down to the OptimizationHints object level. I've been following your issues here and in the graphene library trying to figure out if n+1 query issues are a problem with graphene still before switching my project over. (see https://github.com/graphql-python/graphene-django/issues/429) So with that PrefetchConnection override you have there and the optimization hints above you've been able to weed out most n+1 issues?

**Comment by tfoxy** [comment]
Hi! Sorry for the long time. I updated the docs. It's not perfect, but at least it mentions the `resolver_hints` function.
