### ISSUE TITLE
Deploy 0.6.2 to pypi

### ISSUE THREAD

**Issue by mvanlonden** [tfoxy/graphene-django-optimizer#43]
Latest release was not pushed to pypi.

**Comment by NyanKiyoshi** [comment]
Thanks for noticing, the travis file is broken on latest travis update. I will fix it whenever I have two minutes.

**Comment by NyanKiyoshi** [comment]
Thanks again! 0.6.2 was pushed https://pypi.org/project/graphene-django-optimizer/0.6.2/
