### ISSUE TITLE
Resolving variables in nested queries fails

### ISSUE THREAD

**Issue by maarcingebala** [tfoxy/graphene-django-optimizer#5]
I'm trying to run the query with a variable in a subquery (`products(first: $first)`):

```
query Test($id: ID, $first: Int) {
  category(id: $id) {
    products(first: $first) {
      edges {
        node {
          id
        }
      }
    }
  }
}
```

The above would fail with an error: `'Variable' object has no attribute 'value'`. I did some debugging and it seems that the problem happens [in this line](https://github.com/tfoxy/graphene-django-optimizer/blob/master/graphene_django_optimizer/query.py#L175). 

It is assumed that `arg.value` has a `value` field, but instead it is of type `Variable`. The value would have to be looked up in `info.variable_values`.

**Comment by maarcingebala** [comment]
@tfoxy Let me know if you don't have time to work on it, I'll be happy to provide a PR, I figured out some quick solution.

**Comment by tfoxy** [comment]
Hi @maarcingebala . I really don't have the time right now to work on this. But I would be happy to review the PR.
