### ISSUE TITLE
Support for GraphQL core v3

### ISSUE THREAD

**Issue by Ouradze** [tfoxy/graphene-django-optimizer#53]
Hi,

I am trying out Graphene v3 and I think it is not compatible at the time with this library. I have an error at the import of graphene-django-optimizer.

I think the culprit is the change of ResolveInfo `cannot import name 'ResolveInfo' from 'graphql' `: https://github.com/graphql-python/graphql-core/blob/master/src/graphql/__init__.py#L159.

Is support for graphql core v3 on the roadmap ?

**Comment by tfoxy** [comment]
Hi! I can check if something can be done. But I would prefer if someone can do a PR for this as I'm no longer working with Python. If that's the case, I would gladly review it and push to have the changes in master.

**Comment by tfoxy** [comment]
#72 fixed this!
