### ISSUE TITLE
Support for Django 3.x

### ISSUE THREAD

**Issue by magicl** [tfoxy/graphene-django-optimizer#55]
Would it be possible to update to support Django 3.x? This is one of the last deps we have that prevent us from upgrading.

Love the library. Thank you

**Comment by mekhami** [comment]
@tfoxy if you have any rough idea of the work that would go into supporting 3.x, I'd be happy to start working on that. It would be good to know from where to start, though.

**Comment by mekhami** [comment]
I ran the tests for the project on django 3.1.3, and everything passed.

**Comment by Ouradze** [comment]
https://github.com/tfoxy/graphene-django-optimizer/pull/58 should close this?

**Comment by tfoxy** [comment]
As @Ouradze mentioned, closing this as #58 fixed this.
